services:
  nginx:
    build: nginx
    container_name: nginx_server
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/static:/usr/share/nginx/html
      - ./nginx/certs:/etc/ssl/certs
    restart: always
